---
version: "3.8"
services:
  status_bot:
    image: p0t4t0sandwich/joke_bot:latest
    container_name: joke_bot
    environment:
      - TZ=UTC
      - BOT_ID=                            # The ID of the Discord bot
    volumes:
      - /PATH-TO-FOLDER:/joke_bot        # Path to the file storage of the bot.
    restart: unless-stopped
